//
// Created by ainho on 15/05/2024.
//

#ifndef INTERFAZ_GRAFICA_MENU_DECODE_BARCODE_H
#define INTERFAZ_GRAFICA_MENU_DECODE_BARCODE_H


class decode_barcode {

};


#endif //INTERFAZ_GRAFICA_MENU_DECODE_BARCODE_H
